apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2025-03-22T18:37:46Z"
  name: ananya-cr
  resourceVersion: "4083"
  uid: 89e599a3-7abb-4cf1-9cd0-770bafc23236
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - delete
