apiVersion: apps/v1
kind: Deployment
metadata:
  name: ananya-nginx3
  namespace: default 
  labels:
    app: nginx3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx3
  template:
    metadata:
      labels:
        app: nginx3
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
