apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cy5130-rbac
  name: ananya-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "delete"]
